"""add batch_jobs

Revision ID: 003947a775fd
Revises: 59d39ae0be98
Create Date: 2026-09-14 12:03:30.220616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '003947a775fd'
down_revision: Union[str, None] = '59d39ae0be98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lib_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_books', sa.Integer(), nullable=False),
    sa.Column('done_books', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('current_lib_id', sa.Integer(), nullable=True),
    sa.Column('completed_lib_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('failed_lib_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_batch_jobs_created_at', 'batch_jobs', ['created_at'], unique=False)
    op.create_index('ix_batch_jobs_status', 'batch_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_batch_jobs_status', table_name='batch_jobs')
    op.drop_index('ix_batch_jobs_created_at', table_name='batch_jobs')
    op.drop_table('batch_jobs')
    # ### end Alembic commands ###