"""add resume_data to torrents

Revision ID: 201a1dc42ff3
Revises: 341e2d1006e3
Create Date: 2026-09-11 10:33:11.018150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '201a1dc42ff3'
down_revision: Union[str, None] = '341e2d1006e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('torrents', sa.Column('resume_data', sa.LargeBinary(), nullable=True))
    op.add_column('torrents', sa.Column('resume_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('torrents', 'resume_updated_at')
    op.drop_column('torrents', 'resume_data')
    # ### end Alembic commands ###