"""initial schema with torrents

Revision ID: 341e2d1006e3
Revises: 
Create Date: 2026-09-11 09:40:20.633993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '341e2d1006e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Расширения PostgreSQL
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('torrents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info_hash', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('magnet', sa.Text(), nullable=True),
    sa.Column('save_path', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('data_size', sa.BigInteger(), nullable=True),
    sa.Column('files_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('info_hash')
    )
    op.create_table('books',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('torrent_id', sa.Integer(), nullable=False),
    sa.Column('lib_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('authors', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('genres', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('series', sa.Text(), nullable=True),
    sa.Column('series_num', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('annotation', sa.Text(), nullable=True),
    sa.Column('archive_name', sa.Text(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['torrent_id'], ['torrents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('torrent_id', 'lib_id', 'archive_name', name='uq_books_torrent_lib_archive')
    )
    op.create_index('ix_books_archive', 'books', ['torrent_id', 'archive_name'], unique=False)
    op.create_index('ix_books_deleted', 'books', ['is_deleted'], unique=False)
    op.create_index('ix_books_language', 'books', ['language'], unique=False)
    op.create_index('ix_books_lib_id', 'books', ['lib_id'], unique=False)
    op.create_index(op.f('ix_books_torrent_id'), 'books', ['torrent_id'], unique=False)

    # === ДОБАВЛЕНО ВРУЧНУЮ: GIN-индексы и FTS ===
    op.execute(
        "CREATE INDEX ix_books_authors_gin ON books USING GIN (authors)"
    )
    op.execute(
        "CREATE INDEX ix_books_genres_gin ON books USING GIN (genres)"
    )
    op.execute(
        "CREATE INDEX ix_books_title_trgm ON books USING GIN (title gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_books_title_fts ON books "
        "USING GIN (to_tsvector('russian', title))"
    )
    # === /ДОБАВЛЕНО ВРУЧНУЮ ===

    op.create_table('library_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torrent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('books_count', sa.Integer(), nullable=True),
    sa.Column('archives_count', sa.Integer(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['torrent_id'], ['torrents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_meta_torrent_id'), 'library_meta', ['torrent_id'], unique=False)
    op.create_table('torrent_files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('torrent_id', sa.Integer(), nullable=False),
    sa.Column('file_index', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('piece_start', sa.Integer(), nullable=False),
    sa.Column('piece_end', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['torrent_id'], ['torrents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('torrent_id', 'file_index', name='uq_torrent_files_idx')
    )
    op.create_index(op.f('ix_torrent_files_torrent_id'), 'torrent_files', ['torrent_id'], unique=False)
    op.create_index('ix_torrent_files_torrent_path', 'torrent_files', ['torrent_id', 'path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_torrent_files_torrent_path', table_name='torrent_files')
    op.drop_index(op.f('ix_torrent_files_torrent_id'), table_name='torrent_files')
    op.drop_table('torrent_files')
    op.drop_index(op.f('ix_library_meta_torrent_id'), table_name='library_meta')
    op.drop_table('library_meta')

    # === ДОБАВЛЕНО ВРУЧНУЮ: удаляем GIN-индексы ===
    op.execute("DROP INDEX IF EXISTS ix_books_title_fts")
    op.execute("DROP INDEX IF EXISTS ix_books_title_trgm")
    op.execute("DROP INDEX IF EXISTS ix_books_genres_gin")
    op.execute("DROP INDEX IF EXISTS ix_books_authors_gin")
    # === /ДОБАВЛЕНО ВРУЧНУЮ ===

    op.drop_index(op.f('ix_books_torrent_id'), table_name='books')
    op.drop_index('ix_books_lib_id', table_name='books')
    op.drop_index('ix_books_language', table_name='books')
    op.drop_index('ix_books_deleted', table_name='books')
    op.drop_index('ix_books_archive', table_name='books')
    op.drop_table('books')
    op.drop_table('torrents')
    # ### end Alembic commands ###