"""add search fields and trigram indexes

Revision ID: 89738bce34b6
Revises: ddc092e74b28
Create Date: 2026-09-11 12:53:26.817188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '89738bce34b6'
down_revision: Union[str, None] = 'ddc092e74b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('authors_text', sa.Text(), nullable=True))
    op.add_column('books', sa.Column('series_text', sa.Text(), nullable=True))
    # Заполнить существующие данные
    op.execute("""
        UPDATE books SET 
            authors_text = array_to_string(authors, ' '),
            series_text = coalesce(series, '')
    """)

    # Trigram-индексы для быстрого ILIKE
    op.execute("CREATE INDEX ix_books_authors_text_trgm ON books USING GIN (authors_text gin_trgm_ops)")
    op.execute("CREATE INDEX ix_books_series_text_trgm ON books USING GIN (series_text gin_trgm_ops)")
    op.execute("CREATE INDEX ix_books_annotation_trgm ON books USING GIN (annotation gin_trgm_ops)")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_books_annotation_trgm")
    op.execute("DROP INDEX IF EXISTS ix_books_series_text_trgm")
    op.execute("DROP INDEX IF EXISTS ix_books_authors_text_trgm")
    op.drop_column('books', 'series_text')
    op.drop_column('books', 'authors_text')
    # ### end Alembic commands ###