"""add archive_entries

Revision ID: ddc092e74b28
Revises: 201a1dc42ff3
Create Date: 2026-09-11 11:40:59.992002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ddc092e74b28'
down_revision: Union[str, None] = '201a1dc42ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('torrent_file_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('lib_id', sa.Integer(), nullable=True),
    sa.Column('compressed_size', sa.BigInteger(), nullable=False),
    sa.Column('uncompressed_size', sa.BigInteger(), nullable=False),
    sa.Column('local_header_offset', sa.BigInteger(), nullable=False),
    sa.Column('compression', sa.Integer(), nullable=False),
    sa.Column('crc32', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['torrent_file_id'], ['torrent_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('torrent_file_id', 'filename', name='uq_archive_entries_file')
    )
    op.create_index('ix_archive_entries_lib_id', 'archive_entries', ['lib_id'], unique=False)
    op.create_index('ix_archive_entries_tf_id', 'archive_entries', ['torrent_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_archive_entries_tf_id', table_name='archive_entries')
    op.drop_index('ix_archive_entries_lib_id', table_name='archive_entries')
    op.drop_table('archive_entries')
    # ### end Alembic commands ###